# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AcortadorRn.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x41\x63ortadorRn.proto\x12\x0b\x61\x63ortadorrn\"\"\n\x0eRequestUsuario\x12\x10\n\x08username\x18\x01 \x01(\t\" \n\x0cResponseUrls\x12\x10\n\x08jsonUrls\x18\x01 \x01(\t\"!\n\nRequestUrl\x12\x13\n\x0bUrlOriginal\x18\x01 \x01(\t\"\x1e\n\x0bResponseUrl\x12\x0f\n\x07jsonUrl\x18\x01 \x01(\t2\x9d\x01\n\x10\x41\x63ortadorService\x12?\n\nacortarUrl\x12\x17.acortadorrn.RequestUrl\x1a\x18.acortadorrn.ResponseUrl\x12H\n\x0egetUrlsUsuario\x12\x1b.acortadorrn.RequestUsuario\x1a\x19.acortadorrn.ResponseUrlsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AcortadorRn_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTUSUARIO._serialized_start=34
  _REQUESTUSUARIO._serialized_end=68
  _RESPONSEURLS._serialized_start=70
  _RESPONSEURLS._serialized_end=102
  _REQUESTURL._serialized_start=104
  _REQUESTURL._serialized_end=137
  _RESPONSEURL._serialized_start=139
  _RESPONSEURL._serialized_end=169
  _ACORTADORSERVICE._serialized_start=172
  _ACORTADORSERVICE._serialized_end=329
# @@protoc_insertion_point(module_scope)
