# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import AcortadorRn_pb2 as AcortadorRn__pb2


class AcortadorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.acortarUrl = channel.unary_unary(
                '/acortadorrn.AcortadorService/acortarUrl',
                request_serializer=AcortadorRn__pb2.RequestUrl.SerializeToString,
                response_deserializer=AcortadorRn__pb2.ResponseUrl.FromString,
                )
        self.getUrlsUsuario = channel.unary_unary(
                '/acortadorrn.AcortadorService/getUrlsUsuario',
                request_serializer=AcortadorRn__pb2.RequestUsuario.SerializeToString,
                response_deserializer=AcortadorRn__pb2.ResponseUrls.FromString,
                )


class AcortadorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def acortarUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getUrlsUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AcortadorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'acortarUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.acortarUrl,
                    request_deserializer=AcortadorRn__pb2.RequestUrl.FromString,
                    response_serializer=AcortadorRn__pb2.ResponseUrl.SerializeToString,
            ),
            'getUrlsUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.getUrlsUsuario,
                    request_deserializer=AcortadorRn__pb2.RequestUsuario.FromString,
                    response_serializer=AcortadorRn__pb2.ResponseUrls.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'acortadorrn.AcortadorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AcortadorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def acortarUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/acortadorrn.AcortadorService/acortarUrl',
            AcortadorRn__pb2.RequestUrl.SerializeToString,
            AcortadorRn__pb2.ResponseUrl.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getUrlsUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/acortadorrn.AcortadorService/getUrlsUsuario',
            AcortadorRn__pb2.RequestUsuario.SerializeToString,
            AcortadorRn__pb2.ResponseUrls.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
